---
title: "Lesson 6 Problem Set"
output: html_notebook
---

***
### 1. Price Histograms with Facet and COlor
```{r}
# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.
library(ggplot2)
ggplot(diamonds, aes(x=price, fill=cut)) + 
  geom_histogram(bins=50) + 
  scale_fill_brewer(type = 'qual') +
  facet_wrap(~color)

```

*** 
### 2. Price vs Table Colored by Cut
```{r}
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.
ggplot(diamonds, aes(x = table, y = price), color = cut) +
  geom_point(position = position_jitter(), alpha = 0.25) +
  scale_fill_brewer(type = 'qual')
```
***
### 3. Typical Table Value
```{r}

ggplot(aes(x = table, y = price), data = diamonds) +
  geom_point(aes(color = cut), size = 3) +
  # add scale and limits to see typical range easily
  scale_x_continuous(limits = c(50, 70), breaks=seq(50, 70, 1)) +
  scale_color_brewer("cut", type = 'qual', palette = 1)
```
***
### 4. Price vs Volume and Diamond Clarity
```{r}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

diamonds$volume = diamonds$x * diamonds$y * diamonds$z

ggplot(aes(x = volume, y = price), data = subset(diamonds, volume < quantile(diamonds$volume, 0.99))) +
  geom_point(aes(color = clarity)) +
  scale_y_log10() +
  scale_color_brewer(type = 'div')
```
*** 
### 5. Proportion of Friendships Initiated
```{r}
# Many interesting variables are derived from two or more others.
# For example, we might wonder how much of a person's network on
# a service like Facebook the user actively initiated. Two users
# with the same degree (or number of friends) might be very
# different if one initiated most of those connections on the
# service, while the other initiated very few. So it could be
# useful to consider this proportion of existing friendships that
# the user initiated. This might be a good predictor of how active
# a user is compared with their peers, or other traits, such as
# personality (i.e., is this person an extrovert?).

# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.
pf = read.delim('pseudo_facebook.tsv')
pf$prop_initiated = pf$friendships_initiated / pf$friend_count

```
*** 
### 6. prop_initiated vs tenure
```{r}
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# Recall, we created year_joined.bucket in Lesson 5
# by first creating year_joined from the variable tenure.
# Then, we used the cut function on year_joined to create
# four bins or cohorts of users.

# (2004, 2009]
# (2009, 2011]
# (2011, 2012]
# (2012, 2014]

pf$year_joined <- 2014 - ceiling(pf$tenure / 365)
pf$year_joined.bucket <- cut(pf$year_joined, breaks = c(2004, 2009, 2011, 2012, 2014))
ggplot(aes(x = tenure, y = prop_initiated), data = pf) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)
```
***
### 7. Smoothing prop_initiated vs. tenure
```{r}
ggplot(aes(x = 30 * round(tenure / 30), y = prop_initiated), data = pf) +
  geom_line(aes(color = year_joined.bucket), stat = 'summary', fun.y = median)

ggplot(aes(tenure, y = prop_initiated), data = pf) +
  geom_smooth(aes(color = year_joined.bucket))
```
***
### 8. Largest group mean prop_initiated
```{r}
mean(pf$prop_initiated[pf$year_joined.bucket=='(2012,2014]'], na.rm=TRUE)
```

***
### 9. Price/Carat Binned, Faceted, & Colored
```{r}
# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.

# Note: In the link, a color palette of type
# 'div' was used to color the histogram using
# scale_color_brewer(type = 'div')
ggplot(aes(x = cut, y = price/carat), data = diamonds) +
  #geom_point(aes(color = color)) +
  # use geom_jitter to spread the values inside single color bucket
  geom_jitter(aes(color = color), alpha = 1, position = position_jitter(h = 0)) +
  facet_wrap(~ clarity) +
  scale_color_brewer(type = 'div')
```

